#!/bin/bash

echo "post install script running.."

# Copy the .desktop file to the autostart directory
if [ -f "/usr/share/applications/laner-pc.desktop" ]; then    
    # Coping the .desktop file to the autostart directory
    cp /usr/share/applications/laner-pc.desktop "/etc/xdg/autostart/"
    
    # Edit the .desktop file to hide the app window
    sed -i 's|^Exec=.*|Exec=/usr/local/bin/laner-pc --autostart|' /etc/xdg/autostart/laner-pc.desktop

    # Set the correct permissions (for the .desktop file)
    chmod 644 /etc/xdg/autostart/laner-pc.desktop

    # Update desktop database
    update-desktop-database

    echo "Autostart setup completed for all users."

else
    echo "Desktop file not found, skipping autostart setup"
fi